package com.viewfunction.processRepository.extension;

public enum ProcessSpaceEventType {
	PROCESSSTEP_ASSIGNED,
	PROCESSSTEP_CREATED,
	PROCESSSTEP_COMPLETED,
	
	PROCESSINSTANCE_COMPLETED,
	PROCESSINSTANCE_CANCELLED,
	
	PROCESSEXTENSIONSTEP_SUCCESS,
	PROCESSEXTENSIONSTEP_FAILURE,
	PROCESSEXTENSIONSTEP_RETRY_DECREMENTED,
	PROCESSEXTENSIONSTEP_CANCELED	
}